name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
     - dev

jobs:
  lint:
    name: Linting and formatting source code
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          repository: 'ci_cd_tut'
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run format:check
      - run: npm run lint:check

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lint-artifacts
          path: ci_cd_tut
  build:
    name: Building and testing source code
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lint-artifacts
      - run: npm run test
      - run: npm run build
  
    

